-- MySQL Script generated by MySQL Workbench
-- 08/23/14 15:37:20
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Faculties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Faculties` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Faculties` (
  `FacultyID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FacultyID`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Departments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Departments` (
  `DepartmentID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `FacultyID` INT NOT NULL,
  PRIMARY KEY (`DepartmentID`),
  INDEX `fk_Departments_Faculties_idx` (`FacultyID` ASC),
  CONSTRAINT `fk_Departments_Faculties`
    FOREIGN KEY (`FacultyID`)
    REFERENCES `mydb`.`Faculties` (`FacultyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `StudentID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `FacultyID` INT NOT NULL,
  PRIMARY KEY (`StudentID`),
  INDEX `fk_Students_Faculties1_idx` (`FacultyID` ASC),
  CONSTRAINT `fk_Students_Faculties1`
    FOREIGN KEY (`FacultyID`)
    REFERENCES `mydb`.`Faculties` (`FacultyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professors` (
  `ProfessorID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `DepartmentID` INT NOT NULL,
  PRIMARY KEY (`ProfessorID`),
  INDEX `fk_Professors_Departments1_idx` (`DepartmentID` ASC),
  CONSTRAINT `fk_Professors_Departments1`
    FOREIGN KEY (`DepartmentID`)
    REFERENCES `mydb`.`Departments` (`DepartmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Courses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `CourseID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `DepartmentID` INT NOT NULL,
  `ProfessorID` INT NOT NULL,
  PRIMARY KEY (`CourseID`),
  INDEX `fk_Courses_Departments1_idx` (`DepartmentID` ASC),
  INDEX `fk_Courses_Professors1_idx` (`ProfessorID` ASC),
  CONSTRAINT `fk_Courses_Departments1`
    FOREIGN KEY (`DepartmentID`)
    REFERENCES `mydb`.`Departments` (`DepartmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_Professors1`
    FOREIGN KEY (`ProfessorID`)
    REFERENCES `mydb`.`Professors` (`ProfessorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Titles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Titles` (
  `TitleID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TitleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProfessorsTitles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProfessorsTitles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProfessorsTitles` (
  `ProfessorID` INT NOT NULL,
  `TitleID` INT NOT NULL,
  CONSTRAINT `fk_ProfessorsTitles_Professors1`
    FOREIGN KEY (`ProfessorID`)
    REFERENCES `mydb`.`Professors` (`ProfessorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProfessorsTitles_Titles1`
    FOREIGN KEY (`TitleID`)
    REFERENCES `mydb`.`Titles` (`TitleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentsCourses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`StudentsCourses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`StudentsCourses` (
  `StudentID` INT NOT NULL,
  `CourseID` INT NOT NULL,
  CONSTRAINT `fk_StudentsCourses_Students1`
    FOREIGN KEY (`StudentID`)
    REFERENCES `mydb`.`Students` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StudentsCourses_Courses1`
    FOREIGN KEY (`CourseID`)
    REFERENCES `mydb`.`Courses` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
