CREATE TABLE "Books" (
	"BookId" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , 
	"Title" NVARCHAR(100) NOT NULL , 
	"Author" NVARCHAR(50) NOT NULL , 
	"PublishDate" DATETIME, 
	"ISBN" NVARCHAR(50)
);